<?php
// create hit_count function
// This page is called throung 92_Creating_non-Unique_Hitcounter.php

function hit_count(){
	$filename = 'count.txt' ;
	$handle = fopen($filename, 'r') ;
	$current = fread($handle, filesize($filename)) ;
	
	fclose($handle) ;


	echo $current_inc = $current + 1 ;

	$handle = fopen($filename, 'w') ;
	$current = fwrite($handle, $current_inc) ;
	fclose($handle) ;
}



?>